(()=>{'use strict';
const $=id=>document.getElementById(id);
const canvas=$('game');
const ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
const mapCanvas=$('minimap');
const mctx=mapCanvas.getContext('2d',{alpha:false});
const ui={hp:$('hpFill'),stamina:$('staminaFill'),xp:$('xpFill'),level:$('levelText'),zone:$('zoneText'),objective:$('objectiveText'),questTitle:$('questTitle'),questProgress:$('questProgress'),toast:$('toast'),modal:$('modal'),modalTitle:$('modalTitle'),modalBody:$('modalBody'),prompt:$('interactPrompt'),promptText:$('interactText'),badge:$('zoneBadge'),quality:$('qualityBadge'),unsupported:$('unsupported')};
const isTouchDevice=('ontouchstart' in window)||navigator.maxTouchPoints>0;
if(!isTouchDevice){ui.unsupported.classList.remove('hidden');return;}
const device={
  ram:navigator.deviceMemory||4,
  cores:navigator.hardwareConcurrency||4,
  dpr:Math.min(window.devicePixelRatio||1,3),
  width:Math.max(innerWidth,1),height:Math.max(innerHeight,1),
  ios:/iPhone|iPad|iPod/i.test(navigator.userAgent),
  android:/Android/i.test(navigator.userAgent)
};
const tier=device.ram>=8&&device.cores>=6&&device.dpr>=2?'HIGH':device.ram>=4&&device.cores>=4?'MEDIUM':'LOW';
const config={
  HIGH:{dpr:Math.min(device.dpr,2),ambient:150,enemyCap:34,particleCap:90,shadowDetail:1,renderScale:1},
  MEDIUM:{dpr:Math.min(device.dpr,1.5),ambient:105,enemyCap:28,particleCap:60,shadowDetail:.78,renderScale:.92},
  LOW:{dpr:1,ambient:70,enemyCap:20,particleCap:40,shadowDetail:.58,renderScale:.82}
}[tier];
ui.quality.textContent=`${device.ios?'iOS':device.android?'Android':'Mobile'} · ${tier} · ${device.ram}GB RAM`;
let W=innerWidth,H=innerHeight,DPR=config.dpr*config.renderScale,last=performance.now(),time=0,toastTime=0,zoneId='mistwood',entities=[],particles=[],projectiles=[],ambient=[],joy={active:false,id:null,x:0,y:0},look={active:false,id:null,x:0,y:0},worldAnim=0;
const SAVE='aethernfall_save_v4',WORLD={w:2200,h:1450};
const zones={
 mistwood:{name:'Туманный лес',badge:'ЛЕС',base:'#18261f',ground:'#35533e',accent:'#6b9a70',water:'#28535c',objective:'Следуйте к древнему святилищу',quest:'Следы в тумане',next:'stonevale',portal:{x:2070,y:820},camp:{x:390,y:390}},
 stonevale:{name:'Каменная долина',badge:'РУИНЫ',base:'#34352f',ground:'#625e51',accent:'#a08e67',water:'#334950',objective:'Исследуйте руины и победите стража',quest:'Пепел старого мира',next:'mistwood',portal:{x:130,y:780},camp:{x:420,y:420}}
};
const player={x:430,y:430,r:20,hp:240,maxHp:240,stamina:100,maxStamina:100,level:5,xp:35,xpNeed:140,gold:125,damage:31,dir:0,speed:185,attackCd:0,dodgeUntil:0,dodgeCd:0,blocking:false,inv:{wood:0,ore:0,herb:0},equipment:{weapon:'Меч туманных земель',armor:'Панцирь следопыта'},quest:{wood:0,ore:0,raider:0,guardian:0,metScout:false}};
function resize(){W=innerWidth;H=innerHeight;DPR=config.dpr*config.renderScale;canvas.width=Math.max(1,Math.floor(W*DPR));canvas.height=Math.max(1,Math.floor(H*DPR));canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);mctx.setTransform(1,0,0,1,0,0)}
addEventListener('resize',resize,{passive:true});resize();
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function rng(seed){const x=Math.sin(seed*928.371)*43758.5453;return x-Math.floor(x)}
function save(){try{localStorage.setItem(SAVE,JSON.stringify({zoneId,player}))}catch(_){}}
function load(){try{const s=JSON.parse(localStorage.getItem(SAVE)||'null');if(!s)return;zoneId=s.zoneId||zoneId;Object.assign(player,s.player||{});player.inv=Object.assign({wood:0,ore:0,herb:0},player.inv||{});player.equipment=Object.assign({},player.equipment||{});player.quest=Object.assign({wood:0,ore:0,herb:0,raider:0,guardian:0,metScout:false},player.quest||{})}catch(_){}}
load();
function toast(t){ui.toast.textContent=t;ui.toast.style.opacity=1;toastTime=2.2}
function gainXP(n){player.xp+=n;while(player.xp>=player.xpNeed){player.xp-=player.xpNeed;player.level++;player.xpNeed=Math.round(player.xpNeed*1.26);player.maxHp+=18;player.hp=player.maxHp;player.damage+=3;toast('Новый уровень — '+player.level)}}
function makeAmbient(){ambient=[];const count=config.ambient;for(let i=0;i<count;i++){const x=60+rng(i+7)*(WORLD.w-120),y=60+rng(i+91)*(WORLD.h-120);ambient.push({x,y,kind:rng(i+201),scale:.65+rng(i+44)*1.5,rot:rng(i+11)*Math.PI*2,depth:.85+rng(i+56)*.3})}}
function enemy(type,x,y){if(entities.filter(e=>e.type!=='resource').length>=config.enemyCap)return;const d={type,x,y,r:17,hp:100,maxHp:100,speed:68,damage:10,cd:0,hit:0,phase:rng(x+y),depth:.9};if(type==='raider')Object.assign(d,{r:20,hp:135,maxHp:135,speed:74,damage:12});if(type==='boar')Object.assign(d,{r:18,hp:92,maxHp:92,speed:102,damage:9});if(type==='guardian')Object.assign(d,{r:36,hp:560,maxHp:560,speed:48,damage:21});entities.push(d)}
function resource(kind,x,y){entities.push({type:'resource',kind,x,y,r:21,hp:1,maxHp:1,pulse:rng(x*y)*Math.PI*2,depth:.94})}
function resetZone(){entities=[];particles=[];projectiles=[];makeAmbient();const z=zones[zoneId];player.x=z.camp.x+50;player.y=z.camp.y+30;for(let i=0;i<40;i++){const x=180+rng(i+300)*(WORLD.w-360),y=170+rng(i+620)*(WORLD.h-340);enemy(zoneId==='stonevale'&&i%4===0?'boar':(i%3?'raider':'boar'),x,y)}for(let i=0;i<24;i++){const x=160+rng(i+1200)*(WORLD.w-320),y=150+rng(i+1700)*(WORLD.h-300);resource(zoneId==='mistwood'?(i%3===0?'herb':'wood'):(i%3===0?'herb':'ore'),x,y)}if(zoneId==='stonevale')enemy('guardian',1770,720)}
resetZone();
function onScreen(x,y,p=120){const sx=x-player.x+W/2,sy=y-player.y+H/2;return sx>-p&&sy>-p&&sx<W+p&&sy<H+p}
function nearest(filter,max=84){let best=null,bd=max;for(const e of entities)if(e.hp>0&&filter(e)){const d=dist(player,e);if(d<bd){bd=d;best=e}}return best}
function burst(x,y,color,count=10,speed=110){const room=Math.max(0,config.particleCap-particles.length);count=Math.min(count,room);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,v=(.25+Math.random())*speed;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.3+Math.random()*.45,max:.8,size:1.8+Math.random()*3.5,color})}}
function kill(e){e.hp=0;gainXP(e.type==='guardian'?100:18);player.gold+=e.type==='guardian'?80:4+Math.floor(Math.random()*4);if(e.type==='raider')player.quest.raider++;if(e.type==='guardian'){player.quest.guardian++;toast('Страж руин повержен!')}burst(e.x,e.y,e.type==='guardian'?'#d0b5e6':'#e17576',24,150);save()}
function hitTarget(e,dmg,crit=false){e.hp-=dmg;e.hit=.14;burst(e.x,e.y,crit?'#f4d48a':'#f0c7b1',10,120);if(e.hp<=0)kill(e)}
function attack(){if(player.attackCd>0)return;player.attackCd=.42;const target=nearest(e=>e.type!=='resource',105);let a=player.dir;if(target)a=Math.atan2(target.y-player.y,target.x-player.x);player.dir=a;let hit=false;for(const e of entities){if(e.hp<=0||e.type==='resource')continue;const d=dist(player,e);const ea=Math.atan2(e.y-player.y,e.x-player.x),diff=Math.abs(Math.atan2(Math.sin(ea-a),Math.cos(ea-a)));if(d<88+e.r&&diff<.95){hitTarget(e,player.damage,Math.random()<.12);hit=true}}burst(player.x+Math.cos(a)*36,player.y+Math.sin(a)*36,'#e0bd67',hit?10:5,90)}
function dodge(){const now=time;if(player.dodgeCd>now||player.stamina<24)return;player.stamina-=24;player.dodgeCd=now+.78;player.dodgeUntil=now+.24;burst(player.x,player.y,'#91c6cc',12,120)}
function skill(n){if(player.stamina<18)return;player.stamina-=18;if(n===1){const t=nearest(e=>e.type!=='resource',135);if(t)hitTarget(t,Math.round(player.damage*1.7));burst(player.x,player.y,'#8fc4e3',18,150);toast('Разрез ветра')}else if(n===2){const a=player.dir;for(let i=0;i<3&&projectiles.length<12;i++)projectiles.push({x:player.x,y:player.y,vx:Math.cos(a+(i-1)*.16)*420,vy:Math.sin(a+(i-1)*.16)*420,damage:Math.round(player.damage*.75),life:.7,color:'#b6e1e6'})}else{player.hp=Math.min(player.maxHp,player.hp+45);burst(player.x,player.y,'#86c99b',18,95);toast('Второе дыхание')}}
function interact(){const z=zones[zoneId];if(dist(player,z.camp)<95){player.quest.metScout=true;toast('Разведчик: древнее святилище скрыто за туманом.');save();return}const r=nearest(e=>e.type==='resource',85);if(r){const key=r.kind==='wood'?'wood':r.kind==='ore'?'ore':'herb';player.inv[key]++;if(key!=='herb')player.quest[key]++;toast('Получено: '+(key==='wood'?'древесина':key==='ore'?'руда':'трава'));burst(r.x,r.y,'#d7c174',12,100);entities.splice(entities.indexOf(r),1);save();return}if(dist(player,z.portal)<100){zoneId=z.next;resetZone();toast('Загрузка: '+zones[zoneId].name);save();return}toast('Здесь пока нечего использовать')}
function craft(){if(player.inv.wood>=3&&player.inv.ore>=2){player.inv.wood-=3;player.inv.ore-=2;player.damage+=5;player.equipment.weapon='Закалённый меч следопыта';toast('Оружие улучшено: +5 урона');save();closeModal()}else toast('Нужно 3 древесины и 2 руды')}
function inputVector(){let x=joy.x,y=joy.y;const l=Math.hypot(x,y);return l>1?{x:x/l,y:y/l}:{x,y}}
function joyMove(t){const r=$('joystick').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.34;let dx=t.clientX-cx,dy=t.clientY-cy,l=Math.hypot(dx,dy);if(l>max){dx=dx/l*max;dy=dy/l*max}joy.x=dx/max;joy.y=dy/max;$('stick').style.transform=`translate(${dx}px,${dy}px)`}
const joyEl=$('joystick');
joyEl.addEventListener('touchstart',e=>{e.preventDefault();const t=e.changedTouches[0];joy.active=true;joy.id=t.identifier;joyMove(t)},{passive:false});
joyEl.addEventListener('touchmove',e=>{e.preventDefault();for(const t of e.changedTouches)if(t.identifier===joy.id)joyMove(t)},{passive:false});
for(const ev of ['touchend','touchcancel'])joyEl.addEventListener(ev,e=>{for(const t of e.changedTouches)if(t.identifier===joy.id){joy.active=false;joy.id=null;joy.x=joy.y=0;$('stick').style.transform='translate(0,0)'}},{passive:false});
canvas.addEventListener('touchstart',e=>{e.preventDefault();const t=e.changedTouches[0];if(t.clientX<W*.45){return}look.active=true;look.id=t.identifier;look.x=t.clientX;look.y=t.clientY},{passive:false});
canvas.addEventListener('touchmove',e=>{e.preventDefault();if(!look.active)return;for(const t of e.changedTouches)if(t.identifier===look.id){const dx=t.clientX-look.x,dy=t.clientY-look.y;look.x=t.clientX;look.y=t.clientY;player.dir+=dx*.006}},{passive:false});
for(const ev of ['touchend','touchcancel'])canvas.addEventListener(ev,e=>{for(const t of e.changedTouches)if(t.identifier===look.id){look.active=false;look.id=null}},{passive:false});
function setActionHandlers(){document.querySelectorAll('.action').forEach(b=>{const a=b.dataset.act;const start=e=>{e.preventDefault();if(a==='attack')attack();else if(a==='dodge')dodge();else if(a==='block')player.blocking=true;else if(a==='skill1')skill(1);else if(a==='skill2')skill(2);else if(a==='skill3')skill(3);else if(a==='use')interact()};b.addEventListener('touchstart',start,{passive:false});if(a==='block'){for(const ev of ['touchend','touchcancel'])b.addEventListener(ev,()=>player.blocking=false,{passive:false})}})}
setActionHandlers();
$('inventoryBtn').addEventListener('touchstart',e=>{e.preventDefault();openInventory()},{passive:false});$('menuBtn').addEventListener('touchstart',e=>{e.preventDefault();openMenu()},{passive:false});$('modalClose').addEventListener('touchstart',e=>{e.preventDefault();closeModal()},{passive:false});
function showModal(title,body){ui.modalTitle.textContent=title;ui.modalBody.innerHTML=body;ui.modal.classList.remove('hidden')}
function closeModal(){ui.modal.classList.add('hidden')}
function openInventory(){showModal('Сумка и экипировка',`<div class="grid"><div class="card"><h3>Оружие</h3><p>${player.equipment.weapon}<br>Урон: <b>${player.damage}</b></p></div><div class="card"><h3>Броня</h3><p>${player.equipment.armor}<br>Защита: 24</p></div><div class="card"><h3>Ресурсы</h3><p>Древесина: ${player.inv.wood}<br>Руда: ${player.inv.ore}<br>Трава: ${player.inv.herb}</p></div><div class="card"><h3>Валюта</h3><p class="gold">${player.gold} золотых</p></div></div><div class="sectionTitle">СОЗДАНИЕ</div><button class="btn" id="craftBtn">Закалить меч · 3 древесины + 2 руды</button>`);$('craftBtn').addEventListener('touchstart',e=>{e.preventDefault();craft()},{passive:false})}
function openMenu(){showModal('Меню',`<div class="stats"><div class="stat"><b>${player.level}</b>Уровень</div><div class="stat"><b>${Math.round(player.hp)}</b>Здоровье</div><div class="stat"><b>${player.damage}</b>Урон</div></div><div class="sectionTitle">ОПТИМИЗАЦИЯ</div><div class="card"><p>${device.ios?'iOS':device.android?'Android':'Mobile'} · ${tier} профиль · DPR ${DPR.toFixed(2)} · до ${config.particleCap} частиц · ${config.enemyCap} активных врагов.</p></div><div class="sectionTitle">СОХРАНЕНИЕ</div><button class="btn" id="saveBtn">Сохранить прогресс</button>`);$('saveBtn').addEventListener('touchstart',e=>{e.preventDefault();save();toast('Прогресс сохранён');closeModal()},{passive:false})}
function update(dt){time+=dt;player.attackCd=Math.max(0,player.attackCd-dt);player.stamina=clamp(player.stamina+23*dt,0,player.maxStamina);const v=inputVector();const moving=Math.hypot(v.x,v.y)>.06;const speed=(moving?player.speed:0)*(player.blocking?.62:1)*(player.stamina>0?1:0.72);if(moving&&time>=player.dodgeUntil){player.x=clamp(player.x+v.x*speed*dt,80,WORLD.w-80);player.y=clamp(player.y+v.y*speed*dt,80,WORLD.h-80);if(Math.abs(v.x)+Math.abs(v.y)>.1)player.dir=Math.atan2(v.y,v.x)}for(const e of entities){if(e.hp<=0||e.type==='resource')continue;e.cd=Math.max(0,e.cd-dt);e.hit=Math.max(0,e.hit-dt);const d=dist(player,e);if(d<500){const a=Math.atan2(player.y-e.y,player.x-e.x);if(d>e.r+player.r+6){e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}else if(e.cd<=0){e.cd=e.type==='guardian'?1.05:1.35;if(time>=player.dodgeUntil){const dmg=player.blocking?Math.ceil(e.damage*.28):e.damage;player.hp=Math.max(0,player.hp-dmg);burst(player.x,player.y,'#e06d68',6,80);if(player.hp<=0){player.hp=player.maxHp;player.x=zones[zoneId].camp.x;player.y=zones[zoneId].camp.y;toast('Вы возвращены к лагерю')}}}}}for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;let hit=false;for(const e of entities){if(e.hp>0&&e.type!=='resource'&&dist(p,e)<e.r+7){hitTarget(e,p.damage);hit=true;break}}if(hit||p.life<=0)projectiles.splice(i,1)}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt;if(p.life<=0)particles.splice(i,1)}toastTime-=dt;if(toastTime<=0)ui.toast.style.opacity=0;ui.hp.style.width=(player.hp/player.maxHp*100)+'%';ui.stamina.style.width=(player.stamina/player.maxStamina*100)+'%';ui.xp.style.width=(player.xp/player.xpNeed*100)+'%';ui.level.textContent='Ур. '+player.level;const z=zones[zoneId];ui.zone.textContent=z.name;ui.objective.textContent=z.objective;ui.questTitle.textContent=z.quest;ui.questProgress.textContent=player.quest.guardian?'Зона очищена — исследуйте мир':z.objective;ui.badge.textContent=z.badge;const can=dist(player,z.camp)<95||nearest(e=>e.type==='resource',85)||dist(player,z.portal)<100;if(can){ui.prompt.classList.remove('hidden');ui.promptText.textContent=dist(player,z.portal)<100?'Перейти в другую зону':dist(player,z.camp)<95?'Поговорить с разведчиком':'Собрать ресурс'}else ui.prompt.classList.add('hidden');if(Math.random()<dt*.045)save()}
function isoY(y){return y*0.82}
function screenPos(x,y){return{x:x-player.x+W/2,y:isoY(y-player.y)+H/2}}
function drawGround(z){ctx.fillStyle=z.base;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2-player.x,H/2-player.y*0.82);const g=ctx.createLinearGradient(0,0,0,WORLD.h*.82);g.addColorStop(0,z.ground);g.addColorStop(1,z.base);ctx.fillStyle=g;ctx.fillRect(0,0,WORLD.w,WORLD.h*.82);ctx.strokeStyle='rgba(255,255,255,.018)';ctx.lineWidth=1;for(let x=0;x<WORLD.w;x+=100){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD.h*.82);ctx.stroke()}for(let y=0;y<WORLD.h;y+=82){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.w,y);ctx.stroke()}ctx.fillStyle='rgba(10,22,17,.16)';ctx.beginPath();ctx.ellipse(1080,760,730,440,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawAmbient(z){for(const a of ambient){if(!onScreen(a.x,a.y,120))continue;const s=screenPos(a.x,a.y),depth=clamp((a.y/WORLD.h),0,1);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);ctx.rotate(a.rot);if(zoneId==='mistwood'){if(a.kind<.52){ctx.fillStyle=`rgba(38,74,48,${.55+.22*depth})`;ctx.beginPath();ctx.arc(0,-8,16*a.scale,0,Math.PI*2);ctx.arc(12*a.scale,-1,14*a.scale,0,Math.PI*2);ctx.arc(-12*a.scale,1,13*a.scale,0,Math.PI*2);ctx.fill();ctx.fillStyle='#5b4630';ctx.fillRect(-4*a.scale,2*a.scale,8*a.scale,20*a.scale)}else if(a.kind<.78){ctx.fillStyle='rgba(89,121,73,.65)';ctx.beginPath();ctx.ellipse(0,0,13*a.scale,6*a.scale,0,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='rgba(216,198,126,.25)';ctx.fillRect(-2,-2,4,4)}}else{if(a.kind<.58){ctx.fillStyle=`rgba(83,81,74,${.62+.15*depth})`;ctx.beginPath();ctx.moveTo(-14*a.scale,12*a.scale);ctx.lineTo(-8*a.scale,-13*a.scale);ctx.lineTo(9*a.scale,-17*a.scale);ctx.lineTo(17*a.scale,8*a.scale);ctx.lineTo(5*a.scale,17*a.scale);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(210,191,145,.11)';ctx.beginPath();ctx.arc(2,-2,5*a.scale,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='rgba(132,118,89,.28)';ctx.fillRect(-10*a.scale,-2,20*a.scale,4)}}ctx.restore()}}
function drawCamp(z){const c=z.camp,s=screenPos(c.x,c.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(0,24,78,31,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4a3d31';ctx.beginPath();ctx.moveTo(-70,20);ctx.lineTo(-31,-42);ctx.lineTo(7,20);ctx.closePath();ctx.fill();ctx.fillStyle='#846c50';ctx.beginPath();ctx.moveTo(-61,18);ctx.lineTo(-31,-29);ctx.lineTo(-7,18);ctx.closePath();ctx.fill();ctx.fillStyle='#d59c55';ctx.beginPath();ctx.arc(28,14,10+Math.sin(time*5)*2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d6b07d';ctx.fillRect(52,-15,13,30);ctx.fillStyle='#25363b';ctx.beginPath();ctx.arc(58,-27,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ead27c';ctx.font='11px system-ui';ctx.fillText('Разведчик',37,-44);ctx.restore()}
function drawPortal(z){const p=z.portal,s=screenPos(p.x,p.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);const pulse=1+Math.sin(time*3)*.06;ctx.scale(pulse,pulse);ctx.strokeStyle=zoneId==='mistwood'?'#79bdc6':'#d6aa6c';ctx.lineWidth=7;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=18;ctx.beginPath();ctx.ellipse(0,0,35,49,0,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=zoneId==='mistwood'?'rgba(78,159,171,.2)':'rgba(193,135,76,.17)';ctx.beginPath();ctx.ellipse(0,0,27,41,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawEntity(e){if(!onScreen(e.x,e.y,100))return;const s=screenPos(e.x,e.y);ctx.save();ctx.translate(s.x,s.y);const bob=Math.sin(time*3+e.phase)*1.8;ctx.translate(0,bob);const sc=0.86+e.y/WORLD.h*.18;ctx.scale(sc,sc*.82);ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(0,e.r*.8,e.r*1.25,e.r*.48,0,0,Math.PI*2);ctx.fill();if(e.type==='guardian'){ctx.fillStyle=e.hit>0?'#6d5880':'#4f4062';ctx.beginPath();ctx.arc(0,0,e.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c7a86d';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,e.r-6,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#e6ba63';ctx.beginPath();ctx.arc(-10,-3,4,0,Math.PI*2);ctx.arc(10,-3,4,0,Math.PI*2);ctx.fill()}else if(e.type==='boar'){ctx.fillStyle=e.hit>0?'#ad7a5e':'#8f674d';ctx.beginPath();ctx.ellipse(0,0,e.r*1.15,e.r*.78,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e5d9c2';ctx.fillRect(e.r*.38,-4,11,3)}else{ctx.fillStyle=e.hit>0?'#bf7371':'#7f3c45';ctx.beginPath();ctx.arc(0,-2,e.r*.65,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4a3034';ctx.beginPath();ctx.moveTo(-e.r*.75,8);ctx.lineTo(0,e.r*1.05);ctx.lineTo(e.r*.75,8);ctx.lineTo(e.r*.55,-e.r*.6);ctx.lineTo(-e.r*.55,-e.r*.6);ctx.closePath();ctx.fill();ctx.fillStyle='#d8c7ac';ctx.beginPath();ctx.arc(0,-e.r*.72,6,0,Math.PI*2);ctx.fill()}ctx.fillStyle='rgba(7,11,12,.7)';ctx.fillRect(-e.r,-e.r-15,e.r*2,5);ctx.fillStyle=e.type==='guardian'?'#ca91e3':'#de6f72';ctx.fillRect(-e.r,-e.r-15,e.r*2*clamp(e.hp/e.maxHp,0,1),5);ctx.restore()}
function drawResource(e){if(!onScreen(e.x,e.y,90))return;const s=screenPos(e.x,e.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);const p=1+Math.sin(time*3+e.pulse)*.03;ctx.scale(p,p);ctx.fillStyle='rgba(0,0,0,.22)';ctx.beginPath();ctx.ellipse(0,13,20,7,0,0,Math.PI*2);ctx.fill();if(e.kind==='wood'){ctx.fillStyle='#6b4a31';ctx.fillRect(-7,-14,14,28);ctx.fillStyle='#477550';ctx.beginPath();ctx.arc(-8,-15,14,0,Math.PI*2);ctx.arc(8,-11,15,0,Math.PI*2);ctx.arc(0,-27,13,0,Math.PI*2);ctx.fill()}else if(e.kind==='ore'){ctx.fillStyle='#636a75';ctx.beginPath();ctx.moveTo(-19,12);ctx.lineTo(-12,-12);ctx.lineTo(6,-20);ctx.lineTo(20,6);ctx.lineTo(7,18);ctx.closePath();ctx.fill();ctx.fillStyle='#b0d8dc';ctx.beginPath();ctx.arc(3,-3,4,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='#78a86f';for(let i=0;i<5;i++){ctx.rotate(Math.PI*2/5);ctx.beginPath();ctx.ellipse(0,-9,5,12,0,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#dccd73';ctx.beginPath();ctx.arc(0,0,4,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawPlayer(){const s=screenPos(player.x,player.y);ctx.save();ctx.translate(s.x,s.y);ctx.rotate(player.dir);const dodgeState=time<player.dodgeUntil;ctx.globalAlpha=dodgeState?.76:1;ctx.scale(1,.82);ctx.fillStyle='rgba(0,0,0,.33)';ctx.beginPath();ctx.ellipse(0,16,28,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#344f58';ctx.beginPath();ctx.moveTo(-17,12);ctx.lineTo(-12,-13);ctx.lineTo(0,-22);ctx.lineTo(14,-12);ctx.lineTo(18,15);ctx.closePath();ctx.fill();ctx.fillStyle='#e0c7a0';ctx.beginPath();ctx.arc(0,-20,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d8dde0';ctx.beginPath();ctx.moveTo(-12,-26);ctx.quadraticCurveTo(0,-45,15,-26);ctx.lineTo(11,-19);ctx.lineTo(-13,-19);ctx.closePath();ctx.fill();ctx.strokeStyle='#dfbc67';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(4,-3);ctx.lineTo(36,-8);ctx.stroke();ctx.fillStyle='#8bb6b8';ctx.beginPath();ctx.arc(4,-3,3,0,Math.PI*2);ctx.fill();if(player.blocking){ctx.strokeStyle='#b6d9db';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,34,-.95,.95);ctx.stroke()}ctx.restore()}
function drawParticles(){for(const p of particles){if(!onScreen(p.x,p.y,50))continue;const s=screenPos(p.x,p.y);ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(s.x,s.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function drawProjectiles(){for(const p of projectiles){if(!onScreen(p.x,p.y,50))continue;const s=screenPos(p.x,p.y);ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=10;ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawWorld(){const z=zones[zoneId];ctx.clearRect(0,0,W,H);drawGround(z);const drawables=[];for(const a of ambient)if(onScreen(a.x,a.y,120))drawables.push({y:a.y,fn:()=>{const s=screenPos(a.x,a.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);ctx.fillStyle=zoneId==='mistwood'?'rgba(45,82,53,.38)':'rgba(91,87,77,.34)';ctx.beginPath();ctx.arc(0,-6,16*a.scale,0,Math.PI*2);ctx.fill();ctx.restore()}});drawables.push({y:zones[zoneId].camp.y,fn:()=>drawCamp(z)});drawables.push({y:zones[zoneId].portal.y,fn:()=>drawPortal(z)});for(const e of entities)if(e.hp>0)drawables.push({y:e.y,fn:()=>e.type==='resource'?drawResource(e):drawEntity(e)});drawables.push({y:player.y,fn:drawPlayer});drawables.sort((a,b)=>a.y-b.y);for(const d of drawables)d.fn();drawProjectiles();drawParticles()}
function drawMap(){const z=zones[zoneId];mctx.clearRect(0,0,240,240);mctx.fillStyle=z.ground;mctx.fillRect(0,0,240,240);mctx.strokeStyle='rgba(255,255,255,.05)';for(let i=0;i<8;i++){mctx.beginPath();mctx.moveTo(i*30,0);mctx.lineTo(i*30,240);mctx.stroke();mctx.beginPath();mctx.moveTo(0,i*30);mctx.lineTo(240,i*30);mctx.stroke()}for(const e of entities){if(e.hp<=0||e.type==='resource')continue;mctx.fillStyle=e.type==='guardian'?'#d29ae7':'#ca6a6e';mctx.fillRect(e.x/WORLD.w*240,e.y/WORLD.h*240,2.5,2.5)}const c=z.camp;mctx.fillStyle='#e6c874';mctx.beginPath();mctx.arc(c.x/WORLD.w*240,c.y/WORLD.h*240,3,0,Math.PI*2);mctx.fill();const p=z.portal;mctx.fillStyle='#79c0d0';mctx.beginPath();mctx.arc(p.x/WORLD.w*240,p.y/WORLD.h*240,3.5,0,Math.PI*2);mctx.fill();mctx.fillStyle='#eef5ef';mctx.beginPath();mctx.arc(player.x/WORLD.w*240,player.y/WORLD.h*240,4,0,Math.PI*2);mctx.fill()}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);drawWorld();drawMap();requestAnimationFrame(loop)}
requestAnimationFrame(loop);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=4').catch(()=>{});
})();
