(()=>{'use strict';
const $=id=>document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
const mcanvas=$('minimap'),mctx=mcanvas.getContext('2d',{alpha:false});
const ui={hp:$('hpFill'),stamina:$('staminaFill'),xp:$('xpFill'),level:$('levelText'),zone:$('zoneText'),objective:$('objectiveText'),questTitle:$('questTitle'),questProgress:$('questProgress'),toast:$('toast'),modal:$('modal'),modalTitle:$('modalTitle'),modalBody:$('modalBody'),prompt:$('interactPrompt'),promptText:$('interactText'),badge:$('zoneBadge'),quality:$('qualityBadge'),loading:$('loadingOverlay'),loadText:$('loadingText'),loadFill:$('loadFill')};
const touchCap=('ontouchstart'in window)||navigator.maxTouchPoints>0;
if(!touchCap){ui.loading.classList.remove('hidden');ui.loadText.textContent='Откройте игру на сенсорном устройстве';return;}

// ---------- Device + quality / FPS profile ----------
const device={ram:navigator.deviceMemory||4,cores:navigator.hardwareConcurrency||4,dpr:Math.min(devicePixelRatio||1,3),width:innerWidth,height:innerHeight,ios:/iPhone|iPad|iPod/i.test(navigator.userAgent),android:/Android/i.test(navigator.userAgent)};
const detected=(device.ram>=8&&device.cores>=6)?'very-high':(device.ram>=6&&device.cores>=6)?'high':(device.ram>=4&&device.cores>=4)?'medium':'low';
const QUALITY={low:{render:0.76,ambient:55,enemyCap:18,particles:32,shadow:0.5},medium:{render:0.9,ambient:85,enemyCap:24,particles:52,shadow:0.72},high:{render:1.0,ambient:115,enemyCap:30,particles:72,shadow:0.88},'very-high':{render:1.0,ambient:145,enemyCap:36,particles:96,shadow:1}};
const FPS=[30,40,45,60,90,120];
let settings={quality:localStorage.getItem('aef_quality')||detected,fps:Number(localStorage.getItem('aef_fps')||60)};
if(!QUALITY[settings.quality])settings.quality=detected;
if(!FPS.includes(settings.fps))settings.fps=60;
let profile=QUALITY[settings.quality];
let W=innerWidth,H=innerHeight,DPR=1;let last=performance.now(),frameLast=0,time=0;const textures={};
function updateBadge(){ui.quality.textContent=`${device.ios?'iOS':device.android?'Android':'Mobile'} · ${settings.quality.toUpperCase()} · ${settings.fps} FPS`;}
function applyGraphics(){profile=QUALITY[settings.quality];DPR=Math.max(.75,Math.min(2.2,device.dpr*profile.render));canvas.width=Math.max(1,Math.floor(W*DPR));canvas.height=Math.max(1,Math.floor(H*DPR));canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);updateBadge();makeAmbient();}
function loadTextures(){['grass','stone'].forEach(name=>{const img=new Image();img.onload=()=>{textures[name]=ctx.createPattern(img,'repeat')};img.src=`assets/textures/${name}.png`})}
function resize(){W=innerWidth;H=innerHeight;applyGraphics();}
addEventListener('resize',resize,{passive:true});

const WORLD={w:2200,h:1450};
const zones={
 mistwood:{name:'Туманный лес',badge:'ЛЕС',base:'#15221d',ground:'#344f3c',accent:'#6ea176',water:'#2e646a',objective:'Следуйте к древнему святилищу',quest:'Следы в тумане',next:'stonevale',portal:{x:1980,y:820},scout:{x:390,y:390},camp:{x:340,y:430}},
 stonevale:{name:'Каменная долина',badge:'РУИНЫ',base:'#2f312f',ground:'#625f53',accent:'#b3996d',water:'#3a5054',objective:'Исследуйте руины и победите стража',quest:'Пепел старого мира',next:'mistwood',portal:{x:220,y:760},scout:{x:420,y:420},camp:{x:340,y:430}}
};
const player={x:390,y:430,r:20,hp:240,maxHp:240,stamina:100,maxStamina:100,level:5,xp:35,xpNeed:140,gold:125,damage:31,dir:0,speed:190,attackCd:0,dodgeUntil:0,dodgeCd:0,blocking:false,inv:{wood:0,ore:0,herb:0},equipment:{weapon:'Меч туманных земель',armor:'Панцирь следопыта'},quest:{wood:0,ore:0,raider:0,guardian:0,metScout:false}};
let zoneId='mistwood',entities=[],particles=[],projectiles=[],ambient=[];let interactionLock=0;
const SAVE='aethernfall_save_v5';
function save(){try{localStorage.setItem(SAVE,JSON.stringify({zoneId,player,settings}))}catch(_){} }
function load(){try{const s=JSON.parse(localStorage.getItem(SAVE)||'null');if(!s)return;zoneId=s.zoneId||zoneId;Object.assign(player,s.player||{});player.inv=Object.assign({wood:0,ore:0,herb:0},player.inv||{});player.equipment=Object.assign({weapon:'Меч туманных земель',armor:'Панцирь следопыта'},player.equipment||{});player.quest=Object.assign({wood:0,ore:0,herb:0,raider:0,guardian:0,metScout:false},player.quest||{});if(s.settings){settings=Object.assign(settings,s.settings);if(!QUALITY[settings.quality])settings.quality=detected;if(!FPS.includes(Number(settings.fps)))settings.fps=60;settings.fps=Number(settings.fps)}}catch(_){} }
load();
function toast(t){ui.toast.textContent=t;ui.toast.style.opacity=1;clearTimeout(toast._t);toast._t=setTimeout(()=>ui.toast.style.opacity=0,1900)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function rng(seed){const x=Math.sin(seed*928.371)*43758.5453;return x-Math.floor(x)}
function addEnemy(type,x,y){if(entities.filter(e=>e.type!=='resource').length>=profile.enemyCap)return;const e={type,x,y,r:18,hp:100,maxHp:100,speed:70,damage:10,cd:0,hit:0,seed:rng(x+y)};if(type==='raider')Object.assign(e,{r:21,hp:135,maxHp:135,speed:76,damage:12});if(type==='boar')Object.assign(e,{r:19,hp:92,maxHp:92,speed:104,damage:9});if(type==='guardian')Object.assign(e,{r:38,hp:560,maxHp:560,speed:48,damage:22});entities.push(e)}
function addResource(kind,x,y){entities.push({type:'resource',kind,x,y,r:20,hp:1,maxHp:1,pulse:rng(x*y)*Math.PI*2})}
function makeAmbient(){ambient=[];for(let i=0;i<profile.ambient;i++){ambient.push({x:70+rng(i+7)*(WORLD.w-140),y:70+rng(i+91)*(WORLD.h-140),kind:rng(i+201),scale:.75+rng(i+44)*1.4,rot:rng(i+11)*Math.PI*2})}}
function resetZone(){entities=[];particles=[];projectiles=[];const z=zones[zoneId];player.x=z.camp.x;player.y=z.camp.y;player.dir=0;for(let i=0;i<52;i++){const x=160+rng(i+300)*(WORLD.w-320),y=160+rng(i+620)*(WORLD.h-320);addEnemy(zoneId==='stonevale'&&i%4===0?'boar':(i%3?'raider':'boar'),x,y)}for(let i=0;i<28;i++){const x=160+rng(i+1200)*(WORLD.w-320),y=150+rng(i+1700)*(WORLD.h-300);addResource(zoneId==='mistwood'?(i%3===0?'herb':'wood'):(i%3===0?'herb':'ore'),x,y)}if(zoneId==='stonevale')addEnemy('guardian',1720,720);makeAmbient()}
function burst(x,y,color,count=10,speed=110){const room=Math.max(0,profile.particles-particles.length);count=Math.min(count,room);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,v=(.25+Math.random())*speed;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.34+Math.random()*.42,max:.8,size:1.7+Math.random()*3.4,color})}}
function gainXP(n){player.xp+=n;while(player.xp>=player.xpNeed){player.xp-=player.xpNeed;player.level++;player.xpNeed=Math.round(player.xpNeed*1.26);player.maxHp+=18;player.hp=player.maxHp;player.damage+=3;toast('Новый уровень — '+player.level)}}
function kill(e){e.hp=0;gainXP(e.type==='guardian'?100:18);player.gold+=e.type==='guardian'?80:4+Math.floor(Math.random()*4);if(e.type==='raider')player.quest.raider++;if(e.type==='guardian'){player.quest.guardian++;toast('Страж руин повержен!')}burst(e.x,e.y,e.type==='guardian'?'#ceb1ea':'#e27677',24,155);save()}
function hitTarget(e,dmg){if(e.hp<=0)return;e.hp-=dmg;e.hit=.14;burst(e.x,e.y,'#efcfa8',9,118);if(e.hp<=0)kill(e)}
function nearest(filter,max=120){let best=null,bd=max;for(const e of entities)if(e.hp>0&&filter(e)){const d=dist(player,e);if(d<bd){bd=d;best=e}}return best}
function attack(){if(player.attackCd>0)return;player.attackCd=.45;const target=nearest(e=>e.type!=='resource',120);if(target)player.dir=Math.atan2(target.y-player.y,target.x-player.x);const a=player.dir;let hit=false;for(const e of entities){if(e.hp<=0||e.type==='resource')continue;const d=dist(player,e);const ea=Math.atan2(e.y-player.y,e.x-player.x);const diff=Math.abs(Math.atan2(Math.sin(ea-a),Math.cos(ea-a)));if(d<96+e.r&&diff<1.05){hitTarget(e,player.damage*(Math.random()<.12?1.5:1));hit=true}}burst(player.x+Math.cos(a)*36,player.y+Math.sin(a)*36,'#e4bf69',hit?12:5,95)}
function dodge(){if(player.dodgeCd>time||player.stamina<24)return;player.stamina-=24;player.dodgeCd=time+.78;player.dodgeUntil=time+.25;burst(player.x,player.y,'#91c6cc',14,125)}
function skill(n){if(player.stamina<20){toast('Недостаточно выносливости');return}player.stamina-=20;if(n===1){const a=player.dir;let hits=0;for(const e of entities){if(e.hp<=0||e.type==='resource')continue;const d=dist(player,e),ea=Math.atan2(e.y-player.y,e.x-player.x),diff=Math.abs(Math.atan2(Math.sin(ea-a),Math.cos(ea-a)));if(d<150&&diff<1.25){hitTarget(e,Math.round(player.damage*1.8));hits++}}burst(player.x,player.y,'#8fc4e3',24,160);toast(hits?'Разрез ветра':'Разрез ветра — мимо')}else if(n===2){const a=player.dir;for(let i=0;i<3;i++)projectiles.push({x:player.x+Math.cos(a)*24,y:player.y+Math.sin(a)*24,vx:Math.cos(a+(i-1)*.13)*450,vy:Math.sin(a+(i-1)*.13)*450,damage:Math.round(player.damage*.8),life:.8,color:'#bfe9ee'})}else{player.hp=Math.min(player.maxHp,player.hp+55);burst(player.x,player.y,'#86c99b',18,100);toast('Второе дыхание')}}
function canInteract(){const z=zones[zoneId];return dist(player,z.portal)<115||dist(player,z.scout)<105||!!nearest(e=>e.type==='resource',92)}
function interact(){if(interactionLock>time)return;interactionLock=time+.22;const z=zones[zoneId];if(dist(player,z.portal)<115){transitionZone();return}if(dist(player,z.scout)<105){player.quest.metScout=true;toast('Разведчик: путь к древнему святилищу открыт.');save();return}const r=nearest(e=>e.type==='resource',92);if(r){const key=r.kind==='wood'?'wood':r.kind==='ore'?'ore':'herb';player.inv[key]++;if(key!=='herb')player.quest[key]++;toast('Получено: '+(key==='wood'?'древесина':key==='ore'?'руда':'трава'));burst(r.x,r.y,'#d6c274',12,105);entities.splice(entities.indexOf(r),1);save();return}}
function transitionZone(){ui.loading.classList.remove('hidden');ui.loadFill.style.width='0%';ui.loadText.textContent='Переход: '+zones[zones[zoneId].next].name;let p=0;const start=performance.now();function tick(now){p=Math.min(1,(now-start)/650);ui.loadFill.style.width=(p*100)+'%';if(p<1){requestAnimationFrame(tick);return}zoneId=zones[zoneId].next;resetZone();save();setTimeout(()=>ui.loading.classList.add('hidden'),110);toast(zones[zoneId].name)}requestAnimationFrame(tick)}
function openModal(title,body){ui.modalTitle.textContent=title;ui.modalBody.innerHTML=body;ui.modal.classList.remove('hidden')}
function closeModal(){ui.modal.classList.add('hidden')}
function openInventory(){openModal('Сумка и экипировка',`<div class="grid"><div class="card"><h3>Оружие</h3><p>${player.equipment.weapon}<br>Урон: <b>${player.damage}</b></p></div><div class="card"><h3>Броня</h3><p>${player.equipment.armor}<br>Защита: <b>24</b></p></div><div class="card"><h3>Ресурсы</h3><p>Древесина: ${player.inv.wood}<br>Руда: ${player.inv.ore}<br>Трава: ${player.inv.herb}</p></div><div class="card"><h3>Валюта</h3><p class="gold">${player.gold} золотых</p></div></div><div class="sectionTitle">КРАФТ</div><button class="btn" id="craftBtn">Закалить меч · 3 древесины + 2 руды</button>`);bindTap($('craftBtn'),()=>craft())}
function craft(){if(player.inv.wood>=3&&player.inv.ore>=2){player.inv.wood-=3;player.inv.ore-=2;player.damage+=5;player.equipment.weapon='Закалённый меч следопыта';toast('Оружие улучшено: +5 урона');save();closeModal()}else toast('Нужно 3 древесины и 2 руды')}
function openMenu(){const supports120=('matchMedia'in window&&matchMedia('(min-resolution: 2dppx)').matches);openModal('Настройки',`<div class="stats"><div class="stat"><b>${player.level}</b>Уровень</div><div class="stat"><b>${Math.round(player.hp)}</b>Здоровье</div><div class="stat"><b>${player.damage}</b>Урон</div></div><div class="sectionTitle">КАЧЕСТВО ГРАФИКИ</div><div class="settingRow"><div class="seg" id="qualitySeg">${['low','medium','high','very-high'].map(q=>`<button data-q="${q}" class="${settings.quality===q?'active':''}">${q==='very-high'?'Very High':q[0].toUpperCase()+q.slice(1)}</button>`).join('')}</div><div class="note">Профиль меняет внутреннее разрешение, плотность окружения, лимит врагов и частиц. Настройка применяется сразу.</div></div><div class="sectionTitle">ЧАСТОТА КАДРОВ</div><div class="settingRow"><div class="seg" id="fpsSeg">${FPS.map(f=>`<button data-f="${f}" class="${settings.fps===f?'active':''}">${f}</button>`).join('')}</div><div class="note">Игра не может показать 90/120 FPS на дисплее с физической частотой 60 Гц. В этом случае браузер отдаёт максимум, который поддерживает экран.</div></div><div class="sectionTitle">УСТРОЙСТВО</div><div class="card"><p>${device.ios?'iOS':device.android?'Android':'Mobile'} · ${device.ram} GB RAM* · ${device.cores} CPU cores · DPR ${device.dpr.toFixed(2)}<br>*Если браузер не сообщает RAM, используется консервативная оценка 4 GB.</p></div><div class="sectionTitle">СОХРАНЕНИЕ</div><button class="btn" id="saveBtn">Сохранить прогресс</button>`);document.querySelectorAll('#qualitySeg button').forEach(b=>bindTap(b,()=>{settings.quality=b.dataset.q;localStorage.setItem('aef_quality',settings.quality);applyGraphics();save();openMenu();}));document.querySelectorAll('#fpsSeg button').forEach(b=>bindTap(b,()=>{settings.fps=Number(b.dataset.f);localStorage.setItem('aef_fps',String(settings.fps));updateBadge();save();openMenu();}));bindTap($('saveBtn'),()=>{save();toast('Прогресс сохранён')})}
function bindTap(el,fn){if(!el)return;let fired=false;el.addEventListener('pointerdown',e=>{e.preventDefault();if(fired)return;fired=true;fn();setTimeout(()=>fired=false,120)},{passive:false})}

// ---------- touch controls ----------
const joyEl=$('joystick'),stick=$('stick');const joy={id:null,x:0,y:0};const look={ids:new Set(),lastX:0,lastY:0};
function moveJoy(t){const r=joyEl.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.34;let dx=t.clientX-cx,dy=t.clientY-cy,l=Math.hypot(dx,dy);if(l>max){dx=dx/l*max;dy=dy/l*max}joy.x=dx/max;joy.y=dy/max;stick.style.transform=`translate(${dx}px,${dy}px)`}
joyEl.addEventListener('pointerdown',e=>{e.preventDefault();joy.id=e.pointerId;joyEl.setPointerCapture?.(e.pointerId);moveJoy(e)},{passive:false});joyEl.addEventListener('pointermove',e=>{if(e.pointerId===joy.id){e.preventDefault();moveJoy(e)}},{passive:false});['pointerup','pointercancel'].forEach(ev=>joyEl.addEventListener(ev,e=>{if(e.pointerId===joy.id){joy.id=null;joy.x=joy.y=0;stick.style.transform='translate(0,0)'}},{passive:false}));
canvas.addEventListener('pointerdown',e=>{if(e.clientX<W*.43)return;look.ids.add(e.pointerId);look.lastX=e.clientX;look.lastY=e.clientY;canvas.setPointerCapture?.(e.pointerId)},{passive:false});canvas.addEventListener('pointermove',e=>{if(!look.ids.has(e.pointerId))return;e.preventDefault();const dx=e.clientX-look.lastX;look.lastX=e.clientX;look.lastY=e.clientY;player.dir+=dx*.008},{passive:false});['pointerup','pointercancel'].forEach(ev=>canvas.addEventListener(ev,e=>{look.ids.delete(e.pointerId)},{passive:false}));

document.querySelectorAll('.action').forEach(btn=>{const a=btn.dataset.act;if(a==='block'){btn.addEventListener('pointerdown',e=>{e.preventDefault();player.blocking=true},{passive:false});['pointerup','pointercancel','pointerleave'].forEach(ev=>btn.addEventListener(ev,()=>player.blocking=false,{passive:false}));return}bindTap(btn,()=>{if(a==='attack')attack();else if(a==='dodge')dodge();else if(a==='skill1')skill(1);else if(a==='skill2')skill(2);else if(a==='skill3')skill(3);else if(a==='use')interact()})});
bindTap(ui.prompt,()=>interact());bindTap($('inventoryBtn'),openInventory);bindTap($('menuBtn'),openMenu);bindTap($('modalClose'),closeModal);
// prevent page zoom / gestures
document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});document.addEventListener('gestureend',e=>e.preventDefault(),{passive:false});let lastTouchEnd=0;document.addEventListener('touchend',e=>{const now=Date.now();if(now-lastTouchEnd<=280)e.preventDefault();lastTouchEnd=now},{passive:false});document.addEventListener('touchmove',e=>{if(e.touches.length>1)e.preventDefault()},{passive:false});

function inputVector(){return{x:joy.x,y:joy.y}}
function update(dt){time+=dt;player.attackCd=Math.max(0,player.attackCd-dt);player.stamina=clamp(player.stamina+24*dt,0,player.maxStamina);const v=inputVector();const moving=Math.hypot(v.x,v.y)>.06;let speed=player.speed*(player.blocking?.58:1);if(moving&&time>=player.dodgeUntil){player.x=clamp(player.x+v.x*speed*dt,70,WORLD.w-70);player.y=clamp(player.y+v.y*speed*dt,70,WORLD.h-70);if(Math.abs(v.x)+Math.abs(v.y)>.1)player.dir=Math.atan2(v.y,v.x)}for(const e of entities){if(e.hp<=0||e.type==='resource')continue;e.cd=Math.max(0,e.cd-dt);e.hit=Math.max(0,e.hit-dt);const d=dist(player,e);if(d<520){const a=Math.atan2(player.y-e.y,player.x-e.x);if(d>e.r+player.r+8){e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}else if(e.cd<=0){e.cd=e.type==='guardian'?1.05:1.35;if(time>=player.dodgeUntil){const dmg=player.blocking?Math.ceil(e.damage*.26):e.damage;player.hp=Math.max(0,player.hp-dmg);burst(player.x,player.y,'#e06d68',7,80);if(player.hp<=0){player.hp=player.maxHp;player.x=zones[zoneId].camp.x;player.y=zones[zoneId].camp.y;toast('Вы возвращены к лагерю')}}}}}
for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;let hit=false;for(const e of entities){if(e.hp>0&&e.type!=='resource'&&dist(p,e)<e.r+7){hitTarget(e,p.damage);hit=true;break}}if(hit||p.life<=0)projectiles.splice(i,1)}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt;if(p.life<=0)particles.splice(i,1)}
ui.hp.style.width=(player.hp/player.maxHp*100)+'%';ui.stamina.style.width=(player.stamina/player.maxStamina*100)+'%';ui.xp.style.width=(player.xp/player.xpNeed*100)+'%';ui.level.textContent='Ур. '+player.level;const z=zones[zoneId];ui.zone.textContent=z.name;ui.objective.textContent=z.objective;ui.questTitle.textContent=z.quest;ui.questProgress.textContent=player.quest.metScout?'Следуйте к древнему святилищу':z.objective;ui.badge.textContent=z.badge;const closePortal=dist(player,z.portal)<115,closeScout=dist(player,z.scout)<105,res=nearest(e=>e.type==='resource',92);if(canInteract()){ui.prompt.classList.remove('hidden');ui.promptText.textContent=closePortal?'Перейти в другую локацию':closeScout?'Поговорить с разведчиком':'Собрать ресурс'}else ui.prompt.classList.add('hidden');}
function isoY(v){return v*.82}function screenPos(x,y){return{x:x-player.x+W/2,y:isoY(y-player.y)+H/2}}
function drawGround(z){ctx.fillStyle=z.base;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2-player.x,H/2-player.y*.82);const pat=(zoneId==='mistwood'?textures.grass:textures.stone);if(pat){ctx.save();ctx.globalAlpha=.38;ctx.fillStyle=pat;ctx.fillRect(-100,-100,WORLD.w+200,WORLD.h*.82+200);ctx.restore()}const g=ctx.createLinearGradient(0,0,0,WORLD.h*.82);g.addColorStop(0,z.ground);g.addColorStop(1,z.base);ctx.fillStyle=g;ctx.globalAlpha=.82;ctx.fillRect(-100,-100,WORLD.w+200,WORLD.h*.82+200);ctx.globalAlpha=1;ctx.fillStyle=zoneId==='mistwood'?'rgba(117,165,119,.05)':'rgba(201,176,124,.05)';for(let i=0;i<26;i++){const x=(rng(i+30)*WORLD.w),y=(rng(i+90)*WORLD.h*.82);ctx.beginPath();ctx.arc(x,y,26+rng(i+120)*34,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawAmbient(){for(const a of ambient){if(Math.abs(a.x-player.x)>W+150||Math.abs(a.y-player.y)>H+220)continue;const s=screenPos(a.x,a.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);if(zoneId==='mistwood'){ctx.fillStyle='rgba(46,77,50,.72)';ctx.beginPath();ctx.arc(0,-12,17*a.scale,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(70,103,61,.75)';ctx.beginPath();ctx.arc(-14,-6,11*a.scale,0,Math.PI*2);ctx.arc(14,-5,12*a.scale,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(88,62,40,.92)';ctx.fillRect(-3,4,6,18*a.scale)}else{ctx.fillStyle='rgba(98,94,81,.85)';ctx.beginPath();ctx.moveTo(-15,10);ctx.lineTo(-7,-13);ctx.lineTo(12,-7);ctx.lineTo(18,10);ctx.closePath();ctx.fill()}ctx.restore()}}
function drawCamp(z){const s=screenPos(z.camp.x,z.camp.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(0,18,60,18,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#513a2a';ctx.beginPath();ctx.moveTo(-48,16);ctx.lineTo(0,-27);ctx.lineTo(48,16);ctx.closePath();ctx.fill();ctx.strokeStyle='#a07852';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-42,13);ctx.lineTo(0,-20);ctx.lineTo(42,13);ctx.stroke();ctx.fillStyle='#b87a42';ctx.beginPath();ctx.arc(-20,7,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffd37c';ctx.shadowColor='#e9a65b';ctx.shadowBlur=18;ctx.beginPath();ctx.arc(17,8,9+Math.sin(time*7)*2,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#ead27c';ctx.font='11px system-ui';ctx.fillText('Разведчик',-24,-37);ctx.restore()}
function drawScout(z){const p=z.scout,s=screenPos(p.x,p.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);ctx.fillStyle='rgba(0,0,0,.25)';ctx.beginPath();ctx.ellipse(0,17,25,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2d4650';ctx.beginPath();ctx.moveTo(-15,15);ctx.lineTo(-12,-12);ctx.lineTo(0,-21);ctx.lineTo(14,-11);ctx.lineTo(17,15);ctx.closePath();ctx.fill();ctx.fillStyle='#d6b891';ctx.beginPath();ctx.arc(0,-21,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d8dde0';ctx.beginPath();ctx.moveTo(-12,-27);ctx.quadraticCurveTo(0,-44,14,-28);ctx.lineTo(11,-21);ctx.lineTo(-12,-21);ctx.closePath();ctx.fill();ctx.strokeStyle='#e2bf70';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-4,-2);ctx.lineTo(30,-7);ctx.stroke();ctx.restore()}
function drawPortal(z){const p=z.portal,s=screenPos(p.x,p.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);const pulse=1+Math.sin(time*3)*.07;ctx.scale(pulse,pulse);const col=zoneId==='mistwood'?'#76c2ce':'#d9ad6d';ctx.strokeStyle=col;ctx.lineWidth=7;ctx.shadowColor=col;ctx.shadowBlur=20;ctx.beginPath();ctx.ellipse(0,0,38,53,0,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=zoneId==='mistwood'?'rgba(69,168,178,.18)':'rgba(194,139,80,.18)';ctx.beginPath();ctx.ellipse(0,0,29,43,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawResource(e){const s=screenPos(e.x,e.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);const c=e.kind==='wood'?'#6aa364':e.kind==='ore'?'#9b9ba5':'#8ab66e';ctx.fillStyle='rgba(0,0,0,.2)';ctx.beginPath();ctx.ellipse(0,16,17,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=c;if(e.kind==='ore'){ctx.beginPath();ctx.moveTo(-12,8);ctx.lineTo(-3,-15);ctx.lineTo(14,-6);ctx.lineTo(8,10);ctx.closePath();ctx.fill();ctx.fillStyle='#d9e1e4';ctx.beginPath();ctx.arc(4,-3,3,0,Math.PI*2);ctx.fill()}else if(e.kind==='wood'){ctx.fillRect(-4,-4,8,22);ctx.beginPath();ctx.arc(-9,-8,12,0,Math.PI*2);ctx.arc(8,-6,11,0,Math.PI*2);ctx.fill()}else{for(let i=0;i<5;i++){ctx.beginPath();ctx.arc((i-2)*6,-7+(i%2)*5,6,0,Math.PI*2);ctx.fill()}}ctx.restore()}
function drawEntity(e){const s=screenPos(e.x,e.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);const h=e.hit>0?.35:1;ctx.globalAlpha=h;ctx.fillStyle='rgba(0,0,0,.25)';ctx.beginPath();ctx.ellipse(0,16,e.r*1.35,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=e.type==='guardian'?'#7b5c87':e.type==='raider'?'#9c4d56':'#6b4d38';ctx.beginPath();ctx.arc(0,0,e.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d6b891';ctx.beginPath();ctx.arc(0,-e.r*.82,e.r*.45,0,Math.PI*2);ctx.fill();if(e.type==='guardian'){ctx.strokeStyle='#d7b56b';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-e.r*.65,-e.r*.15);ctx.lineTo(e.r*.7,-e.r*.7);ctx.stroke()}else{ctx.fillStyle='#161d1b';ctx.fillRect(-e.r*.45,-e.r*.92,e.r*.9,4)}const hpw=e.r*2.1;ctx.fillStyle='rgba(0,0,0,.48)';ctx.fillRect(-hpw/2,-e.r-15,hpw,4);ctx.fillStyle=e.type==='guardian'?'#d8a1e8':'#df6f73';ctx.fillRect(-hpw/2,-e.r-15,hpw*(e.hp/e.maxHp),4);ctx.restore()}
function drawPlayer(){const s=screenPos(player.x,player.y);ctx.save();ctx.translate(s.x,s.y);ctx.scale(1,.82);ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(0,18,30,10,0,0,Math.PI*2);ctx.fill();const dodgeState=time<player.dodgeUntil;if(dodgeState)ctx.globalAlpha=.72;ctx.fillStyle='#2f505c';ctx.beginPath();ctx.moveTo(-18,14);ctx.lineTo(-14,-13);ctx.lineTo(0,-24);ctx.lineTo(15,-13);ctx.lineTo(18,14);ctx.closePath();ctx.fill();ctx.fillStyle='#e0c7a0';ctx.beginPath();ctx.arc(0,-21,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d8dde0';ctx.beginPath();ctx.moveTo(-13,-28);ctx.quadraticCurveTo(0,-47,15,-28);ctx.lineTo(11,-20);ctx.lineTo(-13,-20);ctx.closePath();ctx.fill();ctx.save();ctx.rotate(Math.atan2(Math.sin(player.dir),Math.cos(player.dir)));ctx.strokeStyle='#dfbc67';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(5,-3);ctx.lineTo(38,-11);ctx.stroke();ctx.restore();if(player.blocking){ctx.strokeStyle='#b8d9dc';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,37,-.95,.95);ctx.stroke()}ctx.restore()}
function drawProjectiles(){for(const p of projectiles){const s=screenPos(p.x,p.y);ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawParticles(){for(const p of particles){const s=screenPos(p.x,p.y);ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(s.x,s.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function drawWorld(){const z=zones[zoneId];ctx.clearRect(0,0,W,H);drawGround(z);drawAmbient();const drawables=[{y:z.camp.y,fn:()=>drawCamp(z)},{y:z.scout.y,fn:()=>drawScout(z)},{y:z.portal.y,fn:()=>drawPortal(z)},{y:player.y,fn:drawPlayer}];for(const e of entities)if(e.hp>0)drawables.push({y:e.y,fn:()=>e.type==='resource'?drawResource(e):drawEntity(e)});drawables.sort((a,b)=>a.y-b.y);for(const d of drawables)d.fn();drawProjectiles();drawParticles()}
function drawMap(){const z=zones[zoneId];mctx.clearRect(0,0,240,240);mctx.fillStyle=z.ground;mctx.fillRect(0,0,240,240);mctx.strokeStyle='rgba(255,255,255,.06)';for(let i=0;i<8;i++){mctx.beginPath();mctx.moveTo(i*30,0);mctx.lineTo(i*30,240);mctx.stroke();mctx.beginPath();mctx.moveTo(0,i*30);mctx.lineTo(240,i*30);mctx.stroke()}for(const e of entities){if(e.hp<=0||e.type==='resource')continue;mctx.fillStyle=e.type==='guardian'?'#d29ae7':'#ca6a6e';mctx.fillRect(e.x/WORLD.w*240,e.y/WORLD.h*240,2.5,2.5)}mctx.fillStyle='#e6c874';mctx.beginPath();mctx.arc(z.scout.x/WORLD.w*240,z.scout.y/WORLD.h*240,3,0,Math.PI*2);mctx.fill();mctx.fillStyle='#79c0d0';mctx.beginPath();mctx.arc(z.portal.x/WORLD.w*240,z.portal.y/WORLD.h*240,3.5,0,Math.PI*2);mctx.fill();mctx.fillStyle='#eef5ef';mctx.beginPath();mctx.arc(player.x/WORLD.w*240,player.y/WORLD.h*240,4,0,Math.PI*2);mctx.fill()}
function renderFrame(now){const interval=1000/settings.fps;if(now-frameLast<interval-1)return;frameLast=now;const dt=Math.min(.035,(now-last)/1000);last=now;update(dt);drawWorld();drawMap();requestAnimationFrame(renderFrame)}
applyGraphics();resetZone();loadTextures();requestAnimationFrame(renderFrame);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=5').catch(()=>{});
})();